export default {
  ACCOUNT: '/account',
  ADMIN: '/admin',
  CHANGE_PASSWORD: '/account/change-password',
  CREATE_SPACEBOX: '/create-spacebox',
  FAQ: '/faq',
  HOME: '/',
  LOGIN_MANAGEMENT: '/account/login-management',
  PASSWORD_FORGET: '/pw-forget',
  SIGN_IN: '/signin',
  SIGN_UP: '/signup',
  SPACE_BASE: '/space',
  SPACE_POST: '/space/:spaceboxSlug/:postSlug',
  SPACE_WITH_SLUG: '/space/:spaceboxSlug',
  VERIFY_EMAIL: '/verify-email',
};
