export default {
  ACCOUNT: '/account',
  ADMIN: '/admin',
  CHANGE_PASSWORD: '/account/change-password',
  CREATE_SPACEBOX: '/create-spacebox',
  EDIT_SPACEBOX_BASE: '/edit-spacebox',
  EDIT_SPACEBOX_WITH_SLUG: '/edit-spacebox/:spaceboxSlug',
  FAQ: '/faq',
  HOME: '/',
  LOGIN_MANAGEMENT: '/account/login-management',
  NOT_FOUND: '/404',
  PASSWORD_FORGET: '/pw-forget',
  SIGN_IN: '/signin',
  SIGN_UP: '/signup',
  SPACE_BASE: '/space',
  SPACE_POST: '/space/:spaceboxSlug/:postSlug',
  SPACE_WITH_SLUG: '/space/:spaceboxSlug',
  TERMS_OF_USE: '/terms-of-use',
  USER_BASE: '/user',
  USER_WITH_SLUG: '/user/:userSlug',
  VERIFY_EMAIL: '/verify-email',
};
