export default {
  ACCOUNT_BASE: '/account',
  ACCOUNT_GENERAL_SETTINGS: '/account#general-settings',
  ACCOUNT_CHANGE_PASSWORD: '/account#change-password',
  ACCOUNT_LOGIN_MANAGEMENT: '/account#login-management',
  ADMIN: '/admin',
  CREATE_SPACEBOX: '/create-spacebox',
  EDIT_SPACEBOX_BASE: '/edit-spacebox',
  EDIT_SPACEBOX_WITH_SLUG: '/edit-spacebox/:spaceboxSlug',
  FAQ: '/faq',
  HOME: '/',
  NOT_FOUND: '/404',
  PASSWORD_FORGET: '/password-forget',
  SIGN_IN: '/signin',
  SIGN_UP: '/signup',
  SPACE_BASE: '/space',
  SPACE_POST: '/space/:spaceboxSlug/:postSlug',
  SPACE_WITH_SLUG: '/space/:spaceboxSlug',
  TERMS_OF_USE: '/terms-of-use',
  TEST: '/test',
  USER_BASE: '/user',
  USER_WITH_SLUG: '/user/:userSlug',
  VERIFY_EMAIL: '/verify-email',
};
